#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevTrends.MvcDonutCaching;
    using Frapid.Web;
    
    #line 1 "..\..\Views\Backend\Layout\Shared\DeleteThemeModal.cshtml"
    using Frapid.WebsiteBuilder;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Backend/Layout/Shared/DeleteThemeModal.cshtml")]
    public partial class _Views_Backend_Layout_Shared_DeleteThemeModal_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Backend_Layout_Shared_DeleteThemeModal_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"ui small modal\"");

WriteLiteral(" id=\"DeleteThemeModal\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"close icon\"");

WriteLiteral("></i>\r\n    <div");

WriteLiteral(" class=\"ui red large header\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 5 "..\..\Views\Backend\Layout\Shared\DeleteThemeModal.cshtml"
   Write(Resources.ProceedWithCaution);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui large header\"");

WriteLiteral(">");

            
            #line 8 "..\..\Views\Backend\Layout\Shared\DeleteThemeModal.cshtml"
                                Write(Html.Raw(Resources.ConfirmThemeDelete));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 10 "..\..\Views\Backend\Layout\Shared\DeleteThemeModal.cshtml"
       Write(Resources.ThemeDeleteWarning);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n\r\n        <div");

WriteLiteral(" class=\"ui negative message\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui small exception header\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Backend\Layout\Shared\DeleteThemeModal.cshtml"
                                              Write(Resources.CannotDeleteThemeBecauseOfError);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </div>\r\n\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"ui content attached segment\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui buttons\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" onclick=\"showDeleteThemeModal();\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\Backend\Layout\Shared\DeleteThemeModal.cshtml"
           Write(Resources.NoDontDeleteThisTheme);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"ui red button\"");

WriteLiteral(" id=\"DeleteThemeButton\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Backend\Layout\Shared\DeleteThemeModal.cshtml"
           Write(Resources.Yes);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
